AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation root template | Nested Stacks"

# Parameter definition
Parameters:
  EnvironmentType:
    Description: "Select environment type: Productive or Non-Productive"
    Type: String
    AllowedValues:
      - prod
      - nonprod
    Default: nonprod

  EnvironmentName:
    Description: "Insert environment name. Example: kloudpepper-test"
    Type: String
    Default: kloudpepper-test

  VpcCIDR:
    Description: "Insert VPC CIDR"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.0/24

  PublicSubnet1CIDR:
    Description: "Insert public subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.128/27

  PublicSubnet2CIDR:
    Description: "Insert public subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.160/27

  PrivateSubnet1CIDR:
    Description: "Insert private subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.0/26

  PrivateSubnet2CIDR:
    Description: "Insert private subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.64/26

  DBPrivateSubnet1CIDR:
    Description: "Insert DB private subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.192/27

  DBPrivateSubnet2CIDR:
    Description: "Insert DB private subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range
    Default: 192.168.10.224/27

  CreateALBCertificate:
    Description: "If you want to create a new certificate, select TRUE; otherwise, select FALSE and insert the certificate's ARN in the OtherARNCertificate option"
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: TRUE

  OtherARNCertificate:
    Description: "Please insert your certificate's ARN uploaded to ACM previously"
    Type: String

  PrivateDomainName:
    Description: "Please insert your private domain. Example: example.com"
    Type: String
    Default: kloudpepper.com

  DesiredCount:
    Description: "Insert the number of desired Tasks to be executed in each ECS Service"
    Type: Number
    Default: 1

  ImageUrlApp:
    Description: "Insert the url of the App container image"
    Type: String
    Default: public.ecr.aws/docker/library/nginx:alpine


Mappings:
  Aurora:
    InstanceTypes:
      prod: "db.t2.medium"      # 2 vCPUs + 4 GB
      nonprod: "db.t2.small"    # 1 vCPUs + 2 GB


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "ENVIRONMENT PARAMETERS"
        Parameters:
          - EnvironmentType
          - EnvironmentName
      -
        Label:
          default: "NETWORK PARAMETERS"
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - DBPrivateSubnet1CIDR
          - DBPrivateSubnet2CIDR
      -
        Label:
          default: "ALB PARAMETERS"
        Parameters:
          - CreateALBCertificate
          - OtherARNCertificate
          - PrivateDomainName
      -
        Label:
          default: "ECS PARAMETERS"
        Parameters:
          - DesiredCount
          - ImageUrlApp


Conditions:
  isTrueCreateCertificate: !Equals [!Ref CreateALBCertificate, TRUE]


# Nested Stacks
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-VPC.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        DBPrivateSubnet1CIDR: !Ref DBPrivateSubnet1CIDR
        DBPrivateSubnet2CIDR: !Ref DBPrivateSubnet2CIDR

  NACLStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-NACL.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBPrivateSubnet1: !GetAtt VPCStack.Outputs.DBPrivateSubnet1
        DBPrivateSubnet2: !GetAtt VPCStack.Outputs.DBPrivateSubnet2

  SGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NACLStack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-SG.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        VpcCIDR: !Ref VpcCIDR

  VPCEndpointStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-VPCEndpoints.yaml
      TimeoutInMinutes: 10
      Parameters:
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        VPCEnpointSecurityGroup: !GetAtt SGStack.Outputs.VPCEnpointSecurityGroup

  EFSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-EFS.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        EFSSecurityGroup: !GetAtt SGStack.Outputs.EFSSecurityGroup

  PCAStack:
    Type: AWS::CloudFormation::Stack
    Condition: isTrueCreateCertificate
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-PCA.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        PrivateDomainName: !Ref PrivateDomainName

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-ALB.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ALBSecurityGroup: !GetAtt SGStack.Outputs.ALBSecurityGroup
        CreateALBCertificate: !Ref CreateALBCertificate
        ACMInternalCertificate: !GetAtt PCAStack.Outputs.ACMInternalCertificate
        OtherARNCertificate: !Ref OtherARNCertificate

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCEndpointStack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-RDS-Aurora.yaml
      TimeoutInMinutes: 60
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        DBPrivateSubnet1: !GetAtt VPCStack.Outputs.DBPrivateSubnet1
        DBPrivateSubnet2: !GetAtt VPCStack.Outputs.DBPrivateSubnet2
        DBSecurityGroup: !GetAtt SGStack.Outputs.DBSecurityGroup
        DBType: !FindInMap [Aurora, InstanceTypes, !Ref EnvironmentType]

  Route53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-Route53.yaml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        AlbCanonicalHostedZoneID: !GetAtt ALBStack.Outputs.AlbCanonicalHostedZoneID
        AlbDNSName: !GetAtt ALBStack.Outputs.AlbDNSName
        PrivateDomainName: !Ref PrivateDomainName
        RDSEnpointAddr: !GetAtt RDSStack.Outputs.RDSEnpointAddr

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${EnvironmentName}.s3.${AWS::URLSuffix}/kloudpepper-ECS-Fargate.yaml
      TimeoutInMinutes: 30
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ECSSecurityGroup: !GetAtt SGStack.Outputs.ECSSecurityGroup
        DesiredCount: !Ref DesiredCount
        ImageUrlApp: !Ref ImageUrlApp
        TargetGroupAPP1: !GetAtt ALBStack.Outputs.TargetGroupAPP1
        TargetGroupAPP2: !GetAtt ALBStack.Outputs.TargetGroupAPP2
        FileSystemId: !GetAtt EFSStack.Outputs.FileSystemId
        AccessPointIdDataApp1: !GetAtt EFSStack.Outputs.AccessPointIdDataApp1
        AccessPointIdDataApp2: !GetAtt EFSStack.Outputs.AccessPointIdDataApp2
        PrivateDomainName: !Ref PrivateDomainName