AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create ALB"

Parameters:
  EnvironmentType:
    Type: String

  EnvironmentName:
    Type: String

  VpcID:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  ALBSecurityGroup:
    Type: String

  CreateALBCertificate:
    Type: String

  ACMInternalCertificate:
    Type: String

  OtherARNCertificate:
    Type: String


Conditions:
  isProdEnvironmentType: !Equals [!Ref EnvironmentType, prod]
  isTrueCreateCertificate: !Equals [!Ref CreateALBCertificate, TRUE]

Resources:
# Create target groups of containers: App1, App2
  TargetGroupAPP1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: "/"
      Port: 80
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 30
      UnhealthyThresholdCount: 10
      TargetType: "ip"
      Matcher:
        HttpCode: "200"
      HealthyThresholdCount: 2
      VpcId: !Ref VpcID
      Name: !Sub ${EnvironmentName}-APP1-TG
      HealthCheckEnabled: true
      TargetGroupAttributes:
        -
          Key: "stickiness.enabled"
          Value: "false"
        -
          Key: "deregistration_delay.timeout_seconds"
          Value: "60"
        -
          Key: "stickiness.type"
          Value: "lb_cookie"
        -
          Key: "stickiness.lb_cookie.duration_seconds"
          Value: "86400"
        -
          Key: "slow_start.duration_seconds"
          Value: "0"
        -
          Key: "load_balancing.algorithm.type"
          Value: "round_robin"

  TargetGroupAPP2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: "/"
      Port: 80
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 30
      UnhealthyThresholdCount: 10
      TargetType: "ip"
      Matcher:
        HttpCode: "200"
      HealthyThresholdCount: 2
      VpcId: !Ref VpcID
      Name: !Sub ${EnvironmentName}-APP2-TG
      HealthCheckEnabled: true
      TargetGroupAttributes:
        -
          Key: "stickiness.enabled"
          Value: "false"
        -
          Key: "deregistration_delay.timeout_seconds"
          Value: "60"
        -
          Key: "stickiness.type"
          Value: "lb_cookie"
        -
          Key: "stickiness.lb_cookie.duration_seconds"
          Value: "86400"
        -
          Key: "slow_start.duration_seconds"
          Value: "0"
        -
          Key: "load_balancing.algorithm.type"
          Value: "round_robin"

# Create Internal ALB
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-ALB
      Scheme: "internal"
      Type: "application"
      Subnets:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      IpAddressType: "ipv4"
      LoadBalancerAttributes:
        -
          Key: "access_logs.s3.enabled"
          Value: "false"
        -
          Key: "idle_timeout.timeout_seconds"
          Value: "60"
        -
          Key: "deletion_protection.enabled"
          Value: !If [isProdEnvironmentType, "true", "false"]
        -
          Key: "routing.http2.enabled"
          Value: "true"
        -
          Key: "routing.http.drop_invalid_header_fields.enabled"
          Value: !If [isProdEnvironmentType, "true", "false"]
      Tags:
        -
          Key: Environment
          Value: !Ref EnvironmentName
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-ALB

# Create HTTPS listener
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: "HTTPS"
      SslPolicy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
      Certificates:
        - CertificateArn: !If [isTrueCreateCertificate, !Ref ACMInternalCertificate, !Ref OtherARNCertificate]
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: "text/plain"
            MessageBody: "Wrong path"
            StatusCode: "503"

# Create forwarding rules
  ListenerRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: "forward"
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref TargetGroupAPP1
                Weight: 1 # 50%
              - TargetGroupArn: !Ref TargetGroupAPP2
                Weight: 1 # 50%
            TargetGroupStickinessConfig:
              Enabled: false
      Conditions:
        - Field: "path-pattern"
          Values:
            - "/demo*"
      ListenerArn: !Ref HTTPSListener
      Priority: 1


Outputs:
  AlbCanonicalHostedZoneID:
    Description: Export ALB ID for Route53
    Value: !GetAtt 'ApplicationLoadBalancer.CanonicalHostedZoneID'

  AlbDNSName:
    Description: Export ALB name for Route53 and CodeBuild
    Value: !GetAtt 'ApplicationLoadBalancer.DNSName'
    Export:
      Name: !Sub ${EnvironmentName}-AlbDNSName

  TargetGroupAPP1:
    Description: Export Target Group for container App1
    Value: !Ref TargetGroupAPP1

  TargetGroupAPP2:
    Description: Export Target Group for container App2
    Value: !Ref TargetGroupAPP2